name: Build Network Optimizer Magisk Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up directory structure
      - name: Set up module structure
        run: |
          mkdir -p NetworkOptimizerMagiskModule/common
          mkdir -p NetworkOptimizerMagiskModule/META-INF/com/google/android
          # Ensure scripts are executable
          chmod +x NetworkOptimizerMagiskModule/service.sh
          chmod +x NetworkOptimizerMagiskModule/common/install.sh
          chmod +x NetworkOptimizerMagiskModule/META-INF/com/google/android/update-binary

      # Create ZIP file
      - name: Create Magisk module ZIP
        run: |
          cd NetworkOptimizerMagiskModule
          zip -r ../NetworkOptimizerMagiskModule.zip .
          cd ..

      # Upload ZIP as artifact
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: NetworkOptimizerMagiskModule
          path: NetworkOptimizerMagiskModule.zip
